name: Dia
api:  3.8.1
version: 2.0
main: Crow\Dia\Main
author: Crow
load: STARTUP
commands:
  tag:
    description: §bMacht tag.
    usage: "/tag"
    permission: time.command
  nacht:
    description: §bMacht nacht.
    usage: "/nacht"
    permission: time.command
  gm0:
    description: §cSetzt dich in den gm0
    usage: "/gm0"
    permission: gamemode.command
  gm2:
    description: §cSetzt dich in den gm2
    usage: "/gm2"
    permission: gamemode.command
  gm1:
    description: §cSetzt dich in den gm1
    usage: "/gm1"
    permission: gamemode.command
  gm3:
    description: §cSetzt dich in den Gamemode 3
    usage: "/gm3"
    permission: gamemode.command
  heal:
    description: §6Füllt deine Herzen auf.
    usage: "/heal"
    permission: heal.command
  food:
    description: §6Füllt deine Hungerleiste auf.
    usage: "/food"
    permission: food.command
   booster:
  description: "Server Booster aktivieren"
permissions:
 booster:
  description: Erlaube die Verwendung aller Booster-Befehle
  default: op
  children:
      booster.command:
        description: Erlaube die Verwendung von /booster
        default: op
      booster.version:
        description: Erlaube die Verwendung der Command /Booster-Version
        default: op
      booster.feed:
        description: Erlaube die Verwendung der Command /Booster-Feed
        default: op
      booster.heal:
        description: Erlaube die Verwendung der Command /Booster-Heal
        default: op
      booster.fly:
        description: Erlaube die Verwendung der Command /Booster-Fly
        default: op
      booster.break:
        description: Erlaube die Verwendung der Command /Booster-Break
        default: op
